#build.yaml is a configuration file where all code generating packages global options can be specified.

targets:
  $default:
    builders:
      json_serializable:
        options:
          include_if_null: false
          explicit_to_json: true



